### ISSUE TITLE
Problem in the train.py file (python 3.6)

### ISSUE THREAD

**Issue by hhhhhhhhhn** [calclavia/music-generator#82]
I get this error message
```
Traceback (most recent call last):
  File "train.py", line 32, in <module>
    main()
  File "train.py", line 15, in main
    models = build_or_load()
  File "/home/jose/DeepJ-icsc/util.py", line 15, in build_or_load
    models = build_models()
  File "/home/jose/DeepJ-icsc/model.py", line 149, in build_models
    notes_out = naxis(time_out, chosen, style)
  File "/home/jose/DeepJ-icsc/model.py", line 111, in f
    dense_layer_cache[l] = Dense(int(x.get_shape()[3]))
TypeError: __int__ returned non-int (type NoneType)
```

**Comment by jliuliu** [comment]
same as above

**Comment by paskahlisanjas** [comment]
I guess you should see https://github.com/calclavia/DeepJ/issues/68 and https://github.com/calclavia/DeepJ/issues/69
